version: "3"

# run like this: 
# docker-compose --env-file dotenv-vpn-test.env -f deployment/docker-compose-vpn-test.yaml up

# then attach second container like this:
# docker run -it --rm  --net=container:deployment_vpn_1 curlimages/curl ipinfo.io

# spin down like this:
# docker-compose -f deployment/docker-compose-vpn-test.yaml down

# Docs:
# https://github.com/bubuntux/nordvpn

services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv4.conf.all.rp_filter=2
    devices:
    - /dev/net/tun
    environment:
    - USER=${VPN_USERNAME}
    - PASS=${VPN_PASSWORD}
    - NETWORK=${VPN_NETWORK}
    ports:
    - 8080:80
    - 9997:9997
  
  jupyter:
    image: crypto-research
    network_mode: service:vpn
    entrypoint: jupyter
    command: ["lab", "--ip=0.0.0.0", "--port=9997"]
    depends_on:
    - vpn

  # nginx:
  #   image: nginx
  #   network_mode: service:vpn
  #   depends_on:
  #   - vpn

